esphome:
  platformio_options:
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.esp-idf.memory_type: qio_opi
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

captive_portal:

psram:
  mode: octal
  speed: 80MHz

output:
  - platform: ledc
    pin: 2
    frequency: 1220
    id: gpio_backlight_pwm

light:
  - platform: monochromatic
    output: gpio_backlight_pwm
    name: ${device_name} Display Backlight
    id: display_backlight
    restore_mode: ALWAYS_ON
    on_turn_on:
      - logger.log: "Display backlight turned on"
      # perhaps the light was turned on remotely, we now want to resume lvgl if it was paused
      - if:
          condition: lvgl.is_paused
          then:
            - logger.log: "LVGL resuming"
            - lvgl.resume:
            - lvgl.widget.redraw:

i2c:
  sda: GPIO19
  scl: GPIO20
  scan: true

display:
  - platform: rpi_dpi_rgb
    id: main_display
    color_order: RGB
    invert_colors: True
    update_interval: never
    auto_clear_enabled: false # takes 2.8 seconds to clear the display
    dimensions:
      width: 800
      height: 480
    de_pin: 40
    hsync_pin: 39
    vsync_pin: 41
    pclk_pin: 0
    pclk_frequency: 12MHz
    # rotation: 180
    data_pins:
      red:
        - 45 #r1
        - 48 #r2
        - 47 #r3
        - 21 #r4
        - 14 #r5
      green:
        - 5 #g0
        - 6 #g1
        - 7 #g2
        - 15 #g3
        - 16 #g4
        - 4 #g5
      blue:
        - 8 #b1
        - 3 #b2
        - 46 #b3
        - 9 #b4
        - 1 #b5

touchscreen:
  platform: gt911
  # transform:
  #   mirror_x: true
  #   mirror_y: true
  on_release: # handle idle wake up
    - if:
        condition: lvgl.is_paused
        then:
          - logger.log: "LVGL resuming"
          - lvgl.resume:
          - lvgl.widget.redraw:
          - light.turn_on: display_backlight
